In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
grid = pd.read_csv('../original_data/grids.csv')
grid = grid[ grid['grid'] == 'standard' ]
grid

          grid  year severity  chs  low  mid  high presumptive
0     standard  2002        1    0   12   12    12        stay
1     standard  2003        1    0   12   12    12        stay
2     standard  2004        1    0   12   12    12        stay
3     standard  2005        1    0   12   12    12        stay
4     standard  2006        1    0   12   12    12        stay
...        ...   ...      ...  ...  ...  ...   ...         ...
1458  standard  2016        9    6  135  158   189      commit
1459  standard  2017        9    6  135  158   189      commit
1460  standard  2018        9    6  135  158   189      commit
1461  standard  2019        9    6  135  158   189      commit
1462  standard  2020        9    6  135  158   189      commit

[1463 rows x 8 columns]

In [5]:
grid_dict = {}
for i in grid.index:
    key_ = str(grid.loc[i,'year']) + '_' + str(grid.loc[i,'severity']) + '_' + str(grid.loc[i,'chs'])
    grid_dict[key_] = int(grid.loc[i,'mid'])

In [6]:
import json

with open('../generated_data/grid_dictionary.json', 'w') as fp:
    json.dump(grid_dict, fp)